config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#home"

  get "/home" => "home#home"

  get "/about" => "home#about"

  resources :posts do
    resources :comments
    resources :assets
    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:create, :destroy, :edit, :update]

  def create
    comment_params = params.require(:comment).permit(:body)
    @p = Post.find params[:post_id]
    @comment = Comment.new comment_params
    @comment.post = @p
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        CommentsMailer.notify_post_owner(@comment).deliver_later
        format.html { redirect_to post_path(@p), notice: "Comment created succussfully!" }
        format.js { render :create_success }
      else
        @comments = @p.comments.order(created_at: :desc)
        @assets = @p.assets.order(created_at: :desc)
        format.html { render "posts/show" }
        format.js { render :create_failure }
      end
    end
  end

  def edit
    @p = Post.find_by_id params[:post_id]
    @comment = Comment.find_by_id params[:id]
    respond_to do |format|
      redirect_to post_path(@p), alert: "Access denied." and return unless can? :edit, @comment
      format.js { render }
    end
  end

  def update
    comment_params = params.require(:comment).permit(:body)
    @p = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@p), notice: "Question updated!" }
        format.js { render :update_success }
      else
        @comments = @p.comments.order(created_at: :desc)
        @assets = @p.assets.order(created_at: :desc)
        format.html { render "posts/show" }
        format.js { render :update_failure }
      end
    end
  end

  def destroy
    @comment = Comment.find_by_id params[:id]
    respond_to do |format|
      if @comment
        redirect_to post_path(params[:post_id]), alert: "Access denied." and return unless can? :destroy, @comment
        @comment.destroy
        format.html { redirect_to post_path(@comment.post), notice: "Comment deleted" }
        format.js { render }
      else
        format.html { redirect_to post_path(params[:post_id]), notice: "Comment already deleted" }
      end
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="well" id="<%= dom_id(comment) %>">
  <%= comment.body %>
  <% if can? :destroy, comment %>
    <%= link_to "Delete", post_comment_path(@p, comment), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure?", disable_with: "deleting..."}, remote: true%>
    <%= link_to "Edit", edit_post_comment_path(@p, comment), class: "btn btn-info pull-right edit_comment", id: "edit_btn_#{dom_id(comment)}", remote: true%>
  <% end %>
  <div class="pull-right owned">
    <%= comment.user.first_name %> <%= comment.user.last_name %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@p, @comment], remote: true do |f| %>
  <%= f.input :body %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/comments/create_failure.js.erb
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/create_success.js.erb
$("#comments").prepend("<%= j(render('/comments/comment', {comment: @comment})) %>");

<% @comment = Comment.new %>
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){ $(this).remove(); });

app/views/comments/edit.js.erb
if (!$("#edit_btn_<%= dom_id(@comment) %>").attr("disabled")) {
  $("#new_comment").replaceWith("<%= j render 'form' %>");
  $("#add_comment_heading").html("Editing Comment...");
  $("#edit_btn_<%= dom_id(@comment) %>").html("Editing...");
  $(".edit_comment.btn").attr("disabled", true);
}

app/views/comments/update_failure.js.erb
$("#new_comment").replaceWith("<%= j render 'form' %>");

app/views/comments/update_success.js.erb
<% dom_comment_id = dom_id(@comment) %>
$("#<%= dom_comment_id %>").replaceWith("<%= j(render('/comments/comment', {comment: @comment})) %>");

<% @comment = Comment.new %>
$("#edit_<%= dom_comment_id %>").replaceWith("<%= j render 'form' %>");
$("#add_comment_heading").html("Add a Comment");
$("#edit_btn_<%= dom_comment_id %>").html("Edit");
$(".edit_comment.btn").attr("disabled", false);