config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#home"

  get "/home" => "home#home"

  get "/about" => "home#about"

  resources :posts do
    resources :comments
    resources :assets
    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true,
                    uniqueness: true


  def favourited_by?(user)
    favourite_for(user).present?
  end

  def favourite_for(user)
    favourites.find_by_user_id user.id
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @p = Post.new
  end

  def create
    @p = Post.new(post_params)
    @p.user = current_user
    if @p.save
      redirect_to(post_path(@p), notice: "Post created!")
    else
      render :new
    end
  end

  def show
    @comments = @p.comments.order(created_at: :desc)
    @comment = Comment.new

    @assets = @p.assets.order(created_at: :desc)
    @asset = Asset.new

  end

  def edit
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :edit, @p
  end

  def update
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :update, @p
    if @p.update post_params
      redirect_to(post_path(@p))
    else
      render :edit
    end
  end

  def index
    @posts = Post.order(updated_at: :desc)
  end

  def destroy
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :destroy, @p
    @p.destroy
    flash[:notice] = "Post deleted successfully"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit([:title, :body, {tag_ids: []}])
  end

  def find_post
    @p = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @p do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.association :tags, as: :check_boxes %>
  <%= f.submit({class: "btn btn-primary"}) %>
<% end %>

app/views/posts/edit.html.erb
<h1 class="page-header">Editing Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1 class="page-header">All Posts</h1>
<%= link_to("New Post", new_post_path, class: "btn btn-primary") %>
<div>
  <% @posts.each do |p| %>
    <div class="well clickable_html">
        <%= p.title %>
        <%= link_to "Show", post_path(p), class: "btn btn-primary btn-sm pull-right", style: "display: none" %>
        <% if can? :manage, p %>
          <div class="pull-right owned">Owned</div>
        <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1 class="page-header">Create New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1 class="page-header"><%= @p.title %></h1>
<p><%= @p.body %></p>
<p>Created by: <%= @p.user.first_name %> <%= @p.user.last_name %></p>

<% if @p.tags.any? %>
  Tagged with:
  <% @p.tags.each do |tag| %>
    <div class="label label-primary"><%= tag.name %></div>
  <% end %>
<% end %>

<h2>Assets</h2>
<% @assets.each do |asset| %>
  <div class="well">
    <%#= image_tag asset.file.url %>
    <%= asset.file %>
    <% if can? :destroy, asset %>
      <%= link_to "Delete", post_asset_path(@p, asset), method: :delete, class: "btn btn-danger pull-right", data: {confirm: "Are you sure?"}%>
    <% end %>
  </div>
<% end %>


<% if can? :edit, @p %>
  <h4>Add an Asset</h4>
  <%= simple_form_for [@p, @asset] do |f| %>
    <%= f.input :file %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>


  <%= link_to "Edit", edit_post_path(@p), class: "btn btn-info btn-sm" %>
<% end %>
<% if can? :destroy, @p %>
  <%= link_to "Delete", post_path(@p), {method: :delete, class: "btn btn-danger btn-sm", data: {confirm: "Are you sure you want to delete this post?"}}%>
<% end %>

<% if user_signed_in? && @p.favourited_by?(current_user) %>
  <%= link_to fa_icon("star"), [@p, @p.favourite_for(current_user)],
                method: :delete, class: "icon-big", id: "favourite", remote: true %>
<% else %>
  <%= link_to fa_icon("star-o"), post_favourites_path(@p), method: :post,
                class: "icon-big", id: "favourite", remote: true %>
<% end %>
<p id="favourite_count">Favourited: <%= pluralize(@p.favourites.count, "time") %></p>

<h2 id="add_comment_heading">Add a Comment</h2>
<%= render "/comments/form" %>

<h2>Comments</h2>
<div id="comments">
  <% @comments.each do |comment| %>
    <%= render "/comments/comment", comment: comment %>
  <% end %>
</div>