config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  root "home#home"

  get "/home" => "home#home"

  get "/about" => "home#about"

  resources :posts do
    resources :comments
    resources :assets
    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Post do |p|
      user == p.user
    end

    can :manage, Comment do |c|
      user == c.user
    end

    can :destroy, Comment do |c|
      user == c.post.user
    end

    can :manage, Asset do |a|
      user == a.post.user
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  validates :file, presence: true
  belongs_to :post

  mount_uploader :file, FileUploader

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true,

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post_id, uniqueness: {scope: :user_id}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :assets, dependent: :destroy

  has_many :favourites, dependent: :destroy
  has_many :favouriting_users, through: :favourites, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true,
                    uniqueness: true


  def favourited_by?(user)
    favourite_for(user).present?
  end

  def favourite_for(user)
    favourites.find_by_user_id user.id
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :favourites, dependent: :nullify
  has_many :favourite_posts, through: :favourites, source: :post

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".strip
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

  end

  def about

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :create, :edit, :update, :destroy]

  def new
    @p = Post.new
  end

  def create
    @p = Post.new(post_params)
    @p.user = current_user
    if @p.save
      redirect_to(post_path(@p), notice: "Post created!")
    else
      render :new
    end
  end

  def show
    @comments = @p.comments.order(created_at: :desc)
    @comment = Comment.new

    @assets = @p.assets.order(created_at: :desc)
    @asset = Asset.new

  end

  def edit
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :edit, @p
  end

  def update
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :update, @p
    if @p.update post_params
      redirect_to(post_path(@p))
    else
      render :edit
    end
  end

  def index
    @posts = Post.order(updated_at: :desc)
  end

  def destroy
    redirect_to post_path(@p), alert: "Access denied." and return unless can? :destroy, @p
    @p.destroy
    flash[:notice] = "Post deleted successfully"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit([:title, :body, {tag_ids: []}])
  end

  def find_post
    @p = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>" ><i class='glyphicon glyphicon-home'></i> Home</a>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to("<i class='glyphicon glyphicon-list-alt'></i> Posts".html_safe, posts_path) %></li>
        <li> <%= link_to("<i class='glyphicon glyphicon-info-sign'></i> About".html_safe, about_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "View Favourites",  favourites_path %></li>
          <li> <%= link_to("Log Out", sessions_path, method: :delete) %></li>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_path %></li>
          <li> <%= link_to "Log In", new_session_path %></li>
        <% end %>
      </ul>
      <% if user_signed_in? %>
        <p class="navbar-text navbar-right">Signed in as <%= "#{current_user.first_name} #{current_user.last_name}" %></p>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "/layouts/nav" %>

    <% if flash[:notice]%>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert]  %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>